
export const bootingStages = [
    { text: "Welcome to FutureOS" },
  { text: "Initializing virtual hardware..." },
  { text: "Bootloader engaged..." },
  { text: "Establishing neural interface..." },
  { text: "Loading UI components..." },
  { text: "Synchronizing time with quantum clock..." },
  { text: "Decrypting user environment..." },
  { text: "Spawning desktop environment..." },
  { text: "Mounting file system..." },
  { text: "Launching core services..." },
  { text: "Finalizing startup sequence..." },
  { text: "System ready. Entering main interface." },
  { text: "Initializing memory grid..." },
  { text: "Configuring holographic bus..." },
  { text: "Authenticating biometric handshake..." },
  { text: "Activating AI companion module..." },
  { text: "Rendering hyperspace background..." },
  { text: "Compiling system shaders..." },
  { text: "Starting nano-processes..." },
  { text: "Verifying secure boot signatures..." },
  { text: "Linking neural processing cores..." },
  { text: "Initializing particle UI renderer..." },
  { text: "Scanning planetary IP layer..." },
  { text: "Encrypting local node cache..." },
  { text: "Injecting interface animations..." },
  { text: "Recalibrating user preferences..." },
  { text: "Synchronizing dimensional filesystems..." },
  { text: "Loading chronosync protocols..." },
  { text: "Activating zero-gravity layout..." },
  { text: "Detecting peripheral anomalies..." },
  { text: "Uploading avatar presence..." },
  { text: "Engaging final security layer..." }
  ];
  